/**
 * `stoneware build` - the production build (CLAUDE.md §11).
 *
 * Two independent outputs:
 *   1. One server bundle, with every route and island statically imported so no
 *      transpilation happens at request time.
 *   2. One client chunk per island, plus a shared runtime chunk, each named by
 *      content hash.
 *
 * Route modules are inlined into the server bundle, but path *matching* still
 * uses `Bun.FileSystemRouter`, so `routes/` must be present at runtime. It is
 * read for its filenames, never for its contents.
 */

import { mkdir, rm } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import { buildIslands } from "../build.ts";
import { loadConfigFile, resolveConfig } from "../config.ts";
import { discoverIslands } from "../islands.ts";
import { Router } from "../router.ts";

export interface BuildResult {
  serverBundle: string;
  islandCount: number;
  routeCount: number;
}

export async function build(root: string): Promise<BuildResult> {
  const userConfig = await loadConfigFile(root);
  const config = resolveConfig({ ...userConfig, root }, false);

  await rm(config.outDir, { recursive: true, force: true });
  await mkdir(config.outDir, { recursive: true });

  // --- Islands: one browser chunk each, plus the shared runtime chunk. -------
  const islands = await discoverIslands(config.islandsDir);
  const { manifest } = await buildIslands({ islands, outDir: config.outDir, dev: false });

  // --- Server: every route inlined into a single bundle. --------------------
  const router = new Router(config.routesDir);
  await router.init();
  const routeFiles = Object.values(router.routes).map((file) => resolve(file));

  const entryPath = join(config.outDir, "server-entry.ts");
  await Bun.write(entryPath, serverEntrySource({ root, routeFiles, islandPaths: islands }));

  const result = await Bun.build({
    entrypoints: [entryPath],
    outdir: config.outDir,
    target: "bun",
    format: "esm",
    minify: false,
    sourcemap: "linked",
    naming: { entry: "server.js" },
  });

  if (!result.success) {
    throw new Error(`Server build failed:\n${result.logs.map(String).join("\n")}`);
  }

  return {
    serverBundle: join(config.outDir, "server.js"),
    islandCount: Object.keys(manifest).length,
    routeCount: routeFiles.length,
  };
}

interface EntrySourceOptions {
  root: string;
  routeFiles: string[];
  islandPaths: { name: string; path: string }[];
}

/**
 * Generate the server entry.
 *
 * Static imports are what make this a real bundle: the routes and islands end
 * up inside `server.js` rather than being pulled off disk per request.
 */
function serverEntrySource(options: EntrySourceOptions): string {
  const toImport = (path: string) => JSON.stringify(path.replace(/\\/g, "/"));

  const lines: string[] = [
    "// Generated by `stoneware build`. Do not edit.",
    `import { createApp } from ${toImport(join(import.meta.dir, "..", "server.ts"))};`,
    `import { loadConfigFile } from ${toImport(join(import.meta.dir, "..", "config.ts"))};`,
    "",
  ];

  options.routeFiles.forEach((file, index) => {
    lines.push(`import * as route${index} from ${toImport(file)};`);
  });
  options.islandPaths.forEach((island, index) => {
    lines.push(`import island${index} from ${toImport(island.path)};`);
  });

  lines.push(
    "",
    `const root = ${JSON.stringify(options.root.replace(/\\/g, "/"))};`,
    "",
    "const preloadedRoutes = new Map([",
    ...options.routeFiles.map(
      (file, index) => `  [${JSON.stringify(resolve(file))}, route${index}],`,
    ),
    "]);",
    "",
    "const preloadedIslands = new Map([",
    ...options.islandPaths.map(
      (island, index) => `  [${JSON.stringify(island.name)}, island${index}],`,
    ),
    "]);",
    "",
    "const userConfig = await loadConfigFile(root);",
    "const app = await createApp(",
    "  { ...userConfig, root },",
    "  { dev: false, preloadedRoutes, preloadedIslands },",
    ");",
    "",
    "const server = Bun.serve({",
    "  port: app.config.port,",
    "  hostname: app.config.hostname,",
    "  fetch: (request) => app.fetch(request),",
    "});",
    "",
    "console.log(`[stoneware] serving on http://${server.hostname}:${server.port}`);",
    "",
  );

  return lines.join("\n");
}

/** Human-readable summary for the CLI. */
export function describeBuild(result: BuildResult, root: string): string {
  return [
    `  server   ${relative(root, result.serverBundle).replace(/\\/g, "/")}`,
    `  routes   ${result.routeCount}`,
    `  islands  ${result.islandCount}`,
  ].join("\n");
}
