/**
 * `stoneware build --target vercel` - emit what Vercel's Bun framework preset
 * looks for.
 *
 * The preset is the reason this is small. Vercel detects a `Bun.serve()` call at
 * module startup in a root-level `server.*` entrypoint and routes every request
 * through it, with no `/api` directory and no routing configuration
 * (https://vercel.com/docs/functions/runtimes/bun). A built Stoneware server
 * already calls `Bun.serve()` at module startup, so the entrypoint is a
 * re-export rather than an adapter: there is no request translation to do, and
 * nothing to keep in sync with the framework's own pipeline.
 *
 * The heavy lifting happened elsewhere. What made Vercel fail was a bundle that
 * baked in its build-time absolute root and rescanned `routes/` per request;
 * that is fixed in the build itself (see cli/build.ts) because it broke every
 * build-here-run-there deployment, not only this one.
 */

import { join } from "node:path";

/** Where Vercel's Bun preset looks for the entrypoint. Root or `src/`, `server.*`. */
const ENTRYPOINT = "server.js";

const VERCEL_CONFIG = "vercel.json";

export interface VercelResult {
  entrypoint: string;
  wroteConfig: boolean;
  configNote: string | null;
}

/**
 * The root entrypoint.
 *
 * A side-effect import, deliberately: the bundle calls `Bun.serve()` as it
 * evaluates, which is exactly the signal the preset detects. Re-exporting a
 * handler instead would mean the server never starts.
 */
function entrypointSource(): string {
  return `// Generated by \`stoneware build --target vercel\`. Do not edit.
//
// Vercel's Bun framework preset detects the Bun.serve() call inside this import
// and routes requests through it. The port and hostname the bundle passes are
// ignored on Vercel and used only when this file is run locally.
import "./.stoneware/server.js";
`;
}

/**
 * Three fields, each load-bearing.
 *
 * `framework: "bun"` selects the preset. Left unset, Vercel treats the project
 * as a static build: the entrypoint is never detected, no function is created,
 * and every path returns 404 while the build log still reports success.
 *
 * `bunVersion` selects the runtime. Without it the function runs on Node, where
 * `Bun.serve` does not exist.
 *
 * `buildCommand` invokes the CLI through Bun directly, which sidesteps shim and
 * shebang resolution in the build image.
 *
 * Note what is *not* here: a `functions` block. Its patterns only match
 * Serverless Functions inside an `api/` directory, so adding one to a preset
 * project fails the build outright with "The pattern server.js doesn't match any
 * Serverless Functions inside the api directory." There is no `includeFiles`
 * equivalent for the preset - which is why the build was made relocatable
 * instead, so there is nothing left to include.
 */
function defaultConfig(): string {
  return (
    JSON.stringify(
      {
        $schema: "https://openapi.vercel.sh/vercel.json",
        framework: "bun",
        bunVersion: "1.x",
        buildCommand: "bun node_modules/stoneware/bin/stoneware.mjs build --target vercel",
      },
      null,
      2,
    ) + "\n"
  );
}

/**
 * Write the Vercel entrypoint, and a `vercel.json` if the project has none.
 *
 * An existing `vercel.json` is never rewritten. It is hand-maintained
 * configuration that may carry redirects, headers or regions, and silently
 * overwriting it to add one field would be a bad trade. The caller reports what
 * is missing instead.
 */
export async function emitVercel(root: string): Promise<VercelResult> {
  const entrypoint = join(root, ENTRYPOINT);
  await Bun.write(entrypoint, entrypointSource());

  const configPath = join(root, VERCEL_CONFIG);
  if (await Bun.file(configPath).exists()) {
    const existing = await Bun.file(configPath).text();
    const missing: string[] = [];
    if (!/"framework"\s*:\s*"bun"/.test(existing)) {
      missing.push('"framework": "bun" (without it no function is created and every path 404s)');
    }
    if (!/"bunVersion"\s*:/.test(existing)) {
      missing.push('"bunVersion": "1.x" (without it the function runs on Node, which has no Bun.serve)');
    }
    if (/"functions"\s*:/.test(existing)) {
      missing.push(
        'remove the "functions" block - its patterns only match an api/ directory, ' +
          "so the preset build fails outright",
      );
    }

    return {
      entrypoint,
      wroteConfig: false,
      configNote:
        missing.length === 0 ? null : `${VERCEL_CONFIG} needs: ${missing.join("; ")}.`,
    };
  }

  await Bun.write(configPath, defaultConfig());
  return { entrypoint, wroteConfig: true, configNote: null };
}
